<a href="https://colab.research.google.com/github/AveryGaoo/PRF_ProgrammingFoundations_notebooks/blob/main/week6_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
c = np.array([1,2,3,4])
print(type(c))

<class 'numpy.ndarray'>


In [4]:
import numpy as np

b = np.array([[1,2,3],[4,5,6]])
shape = b.shape #行：2；列：3
rank = np.ndim(b) #几维数组：2
size = b.size #多少个元素：6

print(shape)
print(rank)
print(size)


(2, 3)
2
6


In [9]:
import numpy as np

arr = np.array([4, 4, 3, 4, 5, 6, 7, 9, 0, 10, 17, 12])
newarr = arr.reshape(3, 4)

print(newarr)
print(np.ndim(newarr)) #几维数组
print("")

print(arr.reshape(2, 2, 3))  # 三维数组 2×2×3
print("")

print(arr.reshape(3, -1))  # -1:自动计算列数 → 3×4
print("")

print(arr.reshape(-1, 4))  # -1:自动计算行数 → 3×4


[[ 4  4  3  4]
 [ 5  6  7  9]
 [ 0 10 17 12]]
2

[[[ 4  4  3]
  [ 4  5  6]]

 [[ 7  9  0]
  [10 17 12]]]

[[ 4  4  3  4]
 [ 5  6  7  9]
 [ 0 10 17 12]]

[[ 4  4  3  4]
 [ 5  6  7  9]
 [ 0 10 17 12]]


In [11]:
import numpy as np

a = np.array([4, 4, 3, 4, 5, 6, 7, 9, 0, 10, 17, 12])   #NumPy数组是可变的（mutable），可以直接修改某个位置的值
a[2] = 50
print(a)

print("")

b = np.array([[1,2,3],
              [4,5,6]])
b[1, 2] = 99
print(b)

[ 4  4 50  4  5  6  7  9  0 10 17 12]

[[ 1  2  3]
 [ 4  5 99]]


In [30]:
import numpy as np

a = np.zeros((2,2)) #这是 NumPy 创建全 0 数组的函数；
print("a:")
print(a)  #默认情况下，生成的 0 是 浮点数 (float)，所以显示为 0.
print("")

a1 = np.zeros((2,2), dtype=int)  #如果想生成整型（int）0，可以加上参数
print("a1:")
print(a1)
print("")

b = np.ones((2,2))  #默认数据类型是 float，所以看到的是 1. 而不是整数 1
print("b:")
print(b)
print("")

b1 = np.full((2,2), 1)
print("b1:")
print(b1)
print("")

c = np.full((2,2), 3)
print("c:")
print(c)

a:
[[0. 0.]
 [0. 0.]]

a1:
[[0 0]
 [0 0]]

b:
[[1. 1.]
 [1. 1.]]

b1:
[[1 1]
 [1 1]]

c:
[[3 3]
 [3 3]]


In [ ]:
import numpy as np

d = np.eye(3)  #创建一个 3×3 的单位矩阵  单位矩阵的特点是：主对角线上的元素都是 1，其他位置都是 0；
print(d)
print("")

d = np.eye(4, dtype = int)
print(d)


In [15]:
#NumPy 中的数组合并：SQL 是通过“键”（key）来连接数据；NumPy 是通过“轴（axis）”来拼接数组的
import numpy as np

a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])

c = np.concatenate((a, b), axis=0) #按行（axis=0）拼接 → 垂直堆叠（vertical stack） 两个数组上下拼接在一起（多了行）。
print(c)
print("")

d = np.concatenate((a, b), axis=1) #按列（axis=1）拼接 → 水平堆叠（horizontal stack）两个数组左右拼接在一起（多了列）
print(d)
print("")

e = np.vstack((a, b))
print(e)
print("")

f = np.hstack((a, b))
print(f)
print("")

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]



对于 二维数组：

垂直拼接 (axis=0)：列数必须相同（同宽才能上下拼）；

水平拼接 (axis=1)：行数必须相同（同高才能左右拼）。

对于 一维数组 hstack/vstack 行为有点不同（看下面示例）。

In [40]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# np.stack 在拼接时会创建一个新的轴，结果维度会增 1
A = np.stack((a,b), axis=0)  # shape (2,2,2) ：两个 2x2 的“块”
B = np.stack((a,b), axis=1)  # shape (2,2,2) ：在另一个轴插入
print(A)

print("")
print("")

print(B)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [1]:
import numpy as np

a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

print("a.shape =", a.shape)
print("b.shape =", b.shape)


a.shape = (2, 2)
b.shape = (2, 2)


In [3]:
c = np.array([[9, 9]])   # shape (1, 2)
print(c.shape)


(1, 2)


In [4]:
if a.shape[1] == c.shape[1]:
    print("✅ 可以垂直拼接")
else:
    print("❌ 列数不同，不能垂直拼接")

if a.shape[0] == c.shape[0]:
    print("✅ 可以水平拼接")
else:
    print("❌ 行数不同，不能水平拼接")

✅ 可以垂直拼接
❌ 行数不同，不能水平拼接


In [27]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1.shape)
print(arr2.shape)
#输出 (3，) 表示一维数组，只有一个轴（axis 0），长度是 3，也就是说数组有 3 个元素
#为什么不是（1，3）？因为它不是二维数组；
print("")

arr3 = np.array([[1, 2, 3]])
print(arr3.shape) # 输出 (1, 3)因为它是二维数组；


(3,)
(3,)

(1, 3)


| 数组类型 | shape     | axis=0 意思   | axis=1 意思         |
| ---- | --------- | ----------- | ----------------- |
| 一维   | (N,)      | 沿唯一方向拼接（变长） | ❌ 不存在             |
| 二维   | (M, N)    | 垂直方向（行数增加）  | 水平方向（列数增加）        |
| 三维   | (X, Y, Z) | 在“块”维度上拼接   | 行或列方向拼接（取决于 axis） |



| 函数                     | 是否创建新维度            | 要求维度是否相同      | 举例效果           |
| ---------------------- | ------------------ | ------------- | -------------- |
| **`np.concatenate()`** | ❌ 不创建新维度（只是沿现有轴拼接） | ✅ 所有数组的维度必须相同 | 拼接：接在后面        |
| **`np.stack()`**       | ✅ 会创建一个新维度         | ✅ 所有数组形状必须相同  | 堆叠：像“叠积木”一样加一层 |


In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

a = np.concatenate((arr1, arr2), axis = 0)  #一维数组，在使用concatenate时，不会增加维度，所以只有axis=0的可能性；
print("a:")
print(a)
print(a.shape)
print("")

b = np.stack((arr1, arr2), axis = 0) #会增加维度,垂直堆叠，增加行数；
print("b:")
print(b)
print(b.shape)
print("")

c = np.stack((arr1, arr2), axis = 1) #⚠️会增加维度，水平堆叠，增加列数；
print("c:")
print(c)
print(c.shape)
print("")

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
D = np.stack((A,B), axis=1)
print("D:")
print(D)
print(D.shape)

a:
[1 2 3 4 5 6]
(6,)

b:
[[1 2 3]
 [4 5 6]]
(2, 3)

c:
[[1 4]
 [2 5]
 [3 6]]
(3, 2)

D:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


np.stack() 会在 axis 指定的地方加一个新维度，
它不会“拼行”或“拼列”，而是在更高维度上组合。

In [2]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print("")

b = a[:3, 1:3] #切片
print(b)
print("")

bCopyA= a[:3, 1:3].copy()
bCopyA[0, 0] = 99
print("bCopyA:")
print(bCopyA)
print("a:")
print(a)
print("")

b[0, 0] = 99
print(a)
print("")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 2  3]
 [ 6  7]
 [10 11]]

bCopyA:
[[99  3]
 [ 6  7]
 [10 11]]
a:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



In [7]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]])
print(a)
print("")

# 花式索引（fancy indexing）：
# a[np.arange(4),b] 的意思是从矩阵a的第i行中，取第b[i]列的元素；
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b])   # np.arange(4) -> [0,1,2,3]
print("")

a[np.arange(4), b] += 10
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[ 1  7  9 14]

[[11  2  3  4]
 [ 5  6 17  8]
 [19 10 11 12]
 [13 24 15 16]]


In [14]:
import numpy as np
grades = np.array([14,12,13,14,15,14,14])
x = np.where(grades == 14)  #where会生成一个bool数组

print(x)
print(x[0])
print(grades[x])

(array([0, 3, 5, 6]),)
[0 3 5 6]
[14 14 14 14]


In [23]:
import numpy as np
e = np.random.random((4,4))
print(e)

[[0.6204235  0.16226693 0.11109153 0.23233991]
 [0.47649702 0.99821131 0.57984535 0.89620476]
 [0.08591971 0.01062314 0.97270487 0.60458068]
 [0.47455572 0.16311199 0.26471882 0.78005358]]


✅ 总结：

· np.random.random((m, n)) → 生成一个形状为 (m, n) 的随机小数矩阵。

· 数值范围：[0, 1)

· 如果想固定随机结果：np.random.seed(数字)
    ⚠️：数字可以是任何整数（如 0, 1, 42）；种子相同 → 随机结果相同；种子不同 → 随机结果不同

| 功能   | `random` 模块       | `np.random`                |
| ---- | ----------------- | -------------------------- |
| 来源   | Python 标准库        | NumPy 库                    |
| 返回   | 单个随机数             | 可生成数组或矩阵                   |
| 典型用法 | `random.random()` | `np.random.random((m, n))` |
| 应用场景 | 简单脚本、游戏           | 科学计算、数据分析、机器学习             |


In [28]:
from numpy import random
x = random.randint(100)   #-> [0,100)
print(x)

y = random.rand()
print(y)

59
0.8490832337225389


| 导入方式                       | 使用方式               | 适用场景                |
| -------------------------- | ------------------ | ------------------- |
| `import numpy as np`       | `np.random.rand()` | 导入整个 NumPy 库，常用，更全面 |
| `from numpy import random` | `random.rand()`    | 只想用随机模块，名字更短、更直接    |


| 函数                    | 功能      | 返回类型  | 范围         | 示例     |
| --------------------- | ------- | ----- | ---------- | ------ |
| `random.randint(100)` | 生成随机整数  | int   | [0, 100)   | 42     |
| `random.rand()`       | 生成随机浮点数 | float | [0.0, 1.0) | 0.7392 |


In [45]:
from numpy import random

#生成随机指定行列的整数数组
x1 = random.randint(100, size = (2))   #-> [0,100)
x2 = random.randint(100, size=(2,3))   #-> [0,100)
print(x1)
print("")
print(x2)
print("")

#生成随机指定行列的小数数组，默认[0,1)范围
#⚠️：rand不支持size参数，直接添加就可以，见下：
y1 = random.rand(2)
y2 = random.rand(2,3)
print(y1)
print("")
print(y2)
print("")

#如果想扩大范围，不仅仅局限于0到1，可以用指定区间函数uniform（）：
z = random.uniform(low=1, high=3, size=(2,3))
print(z)

[24 43]

[[97 61 77]
 [64 54 19]]

[0.91362806 0.33660464]

[[0.53323492 0.19366818 0.70229985]
 [0.06072187 0.77826876 0.2448591 ]]

[[2.75884877 2.07057283 1.00579836]
 [1.76537913 2.66247563 1.53952586]]


✅ 总结

random.normal(loc, scale, size) → 生成正态分布(Normal
Distribution)随机数

参数解释：

loc → 均值（最可能的值）

scale → 标准差（数据的散布程度）

size → 数组大小

In [55]:
from numpy import random
x = random.normal(loc=1, scale=2, size=(2,3)) #99.7% -> [1-3*2, 1+3*2]
print(x)


[[ 2.2596921   0.72212062  2.21844925]
 [ 3.72285395 -0.96795672 -0.05025943]]


1️⃣ 二项分布的概念

Binomial Distribution（二项分布） 是 离散分布（Discrete Distribution）

它描述在 n 次独立试验中，某事件发生的次数。

事件是二元的（Binary）：只有两种可能结果，例如：

扔硬币 → 正面（head）或反面（tail）

是否成功 → 成功或失败

举例：掷 10 次硬币，出现正面的次数就是二项分布随机变量。

In [63]:
from numpy import random
x = random.binomial(n=10, p=0.2, size=10)
print(x)

[4 1 2 2 3 2 3 0 3 5]
